package modelo.dto;
// Generated 15-09-2021 23:35:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

    public TipoUsuario(Integer id) {
        this.id = id;
    }
	
    public TipoUsuario(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoUsuario(String descripcion, Set usuarios) {
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


